# FROM debian:buster-slim
FROM debian:buster-slim as builder

# RUN apk add --no-cache git gcc make
RUN apt update && \
    apt install git gcc make -y

RUN git clone https://github.com/RedisLabs/redis-cluster-proxy.git && \
    cd redis-cluster-proxy && make install

# FROM alpine:3.11
FROM debian:buster-slim

COPY --from=builder /usr/local/bin/redis-cluster-proxy /usr/local/bin

ENTRYPOINT [ "/usr/local/bin/redis-cluster-proxy" ]
