version: "3.7"
services:

  redis-cluster-envoy:
    # 2020-09-15
    image: envoyproxy/envoy-dev@sha256:9901116c862d2d2ac4c42a050a052f3609de5a661a79d222c9d0e6ff20dcc9bc
    command: /usr/local/bin/envoy -c /etc/envoy.yaml -l debug --service-cluster redis-cluster-envoy
    volumes:
      - "./envoy.yaml:/etc/envoy.yaml"
    networks:
      envoymesh:
      redis_net:
        ipv4_address: 172.28.1.1
    ports:
      - "8001:8001"

  redis-1:
    image: redis:6.0.7-alpine
    volumes:
      - "./conf/redis.conf:/etc/redis.conf"
      - redis-1:/data
    command: /etc/redis.conf
    networks:
      envoymesh:
        aliases:
          - redis_server_1
      redis_net:
        ipv4_address: 172.28.1.6
  redis-2:
    image: redis:6.0.7-alpine
    volumes:
      - "./conf/redis.conf:/etc/redis.conf"
      - redis-2:/data
    command: /etc/redis.conf
    networks:
      envoymesh:
        aliases:
          - redis_server_2
      redis_net:
        ipv4_address: 172.28.1.7
  redis-3:
    image: redis:6.0.7-alpine
    volumes:
      - "./conf/redis.conf:/etc/redis.conf"
      - redis-3:/data
    command: /etc/redis.conf
    networks:
      envoymesh:
        aliases:
          - redis_server_3
      redis_net:
        ipv4_address: 172.28.1.8

volumes:
  redis-1:
  redis-2:
  redis-3:

networks:
  redis_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  envoymesh: {}
