version: "3.7"
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy

    volumes:
      - "./envoy.yaml:/etc/envoy.yaml"
    networks:
      - envoymesh
    expose:
      - "1999"
      - "8001"
    ports:
      - "1999:1999"
      - "8001:8001"

  redis-1:
    image: redis:6.0.7-alpine
    volumes:
      - "./conf/redis.conf:/etc/redis.conf"
      - redis-1:/data
    command: /etc/redis.conf
    networks:
      envoymesh:
        aliases:
          - redis_server_1
      redis_net:
        ipv4_address: 172.28.1.6
  redis-2:
    image: redis:6.0.7-alpine
    volumes:
      - "./conf/redis.conf:/etc/redis.conf"
      - redis-2:/data
    command: /etc/redis.conf
    networks:
      envoymesh:
        aliases:
          - redis_server_2
      redis_net:
        ipv4_address: 172.28.1.7
  redis-3:
    image: redis:6.0.7-alpine
    volumes:
      - "./conf/redis.conf:/etc/redis.conf"
      - redis-3:/data
    command: /etc/redis.conf
    networks:
      envoymesh:
        aliases:
          - redis_server_3
      redis_net:
        ipv4_address: 172.28.1.8

volumes:
  redis-1:
  redis-2:
  redis-3:

networks:
  redis_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  envoymesh: {}
